In [1]:
# import dependencies
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
# load resources, 2019 data for training set, 2020Q1 for test set
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [3]:
# print 2019 data
train_df

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,354912,354912,19975.0,0.2565,801.09,RENT,28000.0,Not Verified,high_risk,n,...,100.0,16.7,0.0,0.0,50055.0,28192.0,18700.0,19055.0,N,N
12176,354944,354944,15000.0,0.1774,540.34,RENT,50000.0,Verified,high_risk,n,...,90.5,11.1,0.0,0.0,70324.0,57025.0,13300.0,54824.0,N,N
12177,354973,354973,3600.0,0.1862,131.28,RENT,60000.0,Not Verified,high_risk,n,...,100.0,0.0,0.0,0.0,83765.0,55156.0,14800.0,53065.0,N,N
12178,355002,355002,15000.0,0.0881,475.68,MORTGAGE,62000.0,Source Verified,high_risk,n,...,100.0,0.0,0.0,0.0,189930.0,23748.0,7000.0,32930.0,N,N
12179,355307,355307,15000.0,0.1774,540.34,RENT,54080.0,Not Verified,high_risk,n,...,90.0,100.0,0.0,0.0,48968.0,29786.0,2900.0,33968.0,N,N

In [18]:
# convert categorical data to numeric and separate target feature for testing data
X_train = pd.get_dummies(train_df.drop(columns=['loan_status']))
y_train = train_df['loan_status']
X_train

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,57107,57107,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,...,0,1,0,1,1,0,1,0,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,...,0,1,0,1,1,0,1,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,...,0,1,0,1,1,0,1,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,...,0,1,0,1,1,0,1,0,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,...,0,1,0,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,354912,354912,19975.0,0.2565,801.09,28000.0,28.42,0.0,0.0,15.0,...,0,1,0,1,1,0,1,0,1,0
12176,354944,354944,15000.0,0.1774,540.34,50000.0,23.43,4.0,0.0,16.0,...,1,1,0,1,1,0,1,0,1,0
12177,354973,354973,3600.0,0.1862,131.28,60000.0,28.80,0.0,1.0,14.0,...,0,1,0,1,1,0,1,0,1,0
12178,355002,355002,15000.0,0.0881,475.68,62000.0,11.44,0.0,0.0,5.0,...,0,1,0,1,0,1,1,0,1,0
12179,355307,355307,15000.0,0.1774,540.34,54080.0,21.66,1.0,1.0,5.0,...,0,1,1,0,1,0,1,0,1,0

In [6]:
# verify all types are numerical
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 94 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Unnamed: 0                           12180 non-null  int64
 1   index                                12180 non-null  int64
 2   loan_amnt                            12180 non-null  float64
 3   int_rate                             12180 non-null  float64
 4   installment                          12180 non-null  float64
 5   annual_inc                           12180 non-null  float64
 6   dti                                  12180 non-null  float64
 7   delinq_2yrs                          12180 non-null  float64
 8   inq_last_6mths                       12180 non-null  float64
 9   open_acc                             12180 non-null  float64
 10  pub_rec                              12180 non-null  float64
 11  revol_bal                            12180 non-null  float64
 12  total_acc                            12180 non-null  float64
 13  out_prncp                            12180 non-null  float64
 14  out_prncp_inv                        12180 non-null  float64
 15  total_pymnt                          12180 non-null  float64
 16  total_pymnt_inv                      12180 non-null  float64
 17  total_rec_prncp                      12180 non-null  float64
 18  total_rec_int                        12180 non-null  float64
 19  total_rec_late_fee                   12180 non-null  float64
 20  recoveries                           12180 non-null  float64
 21  collection_recovery_fee              12180 non-null  float64
 22  last_pymnt_amnt                      12180 non-null  float64
 23  collections_12_mths_ex_med           12180 non-null  float64
 24  policy_code                          12180 non-null  float64
 25  acc_now_delinq                       12180 non-null  float64
 26  tot_coll_amt                         12180 non-null  float64
 27  tot_cur_bal                          12180 non-null  float64
 28  open_acc_6m                          12180 non-null  float64
 29  open_act_il                          12180 non-null  float64
 30  open_il_12m                          12180 non-null  float64
 31  open_il_24m                          12180 non-null  float64
 32  mths_since_rcnt_il                   12180 non-null  float64
 33  total_bal_il                         12180 non-null  float64
 34  il_util                              12180 non-null  float64
 35  open_rv_12m                          12180 non-null  float64
 36  open_rv_24m                          12180 non-null  float64
 37  max_bal_bc                           12180 non-null  float64
 38  all_util                             12180 non-null  float64
 39  total_rev_hi_lim                     12180 non-null  float64
 40  inq_fi                               12180 non-null  float64
 41  total_cu_tl                          12180 non-null  float64
 42  inq_last_12m                         12180 non-null  float64
 43  acc_open_past_24mths                 12180 non-null  float64
 44  avg_cur_bal                          12180 non-null  float64
 45  bc_open_to_buy                       12180 non-null  float64
 46  bc_util                              12180 non-null  float64
 47  chargeoff_within_12_mths             12180 non-null  float64
 48  delinq_amnt                          12180 non-null  float64
 49  mo_sin_old_il_acct                   12180 non-null  float64
 50  mo_sin_old_rev_tl_op                 12180 non-null  float64
 51  mo_sin_rcnt_rev_tl_op                12180 non-null  float64
 52  mo_sin_rcnt_tl                       12180 non-null  float64
 53  mort_acc                             12180 non-null  float64
 54  mths_since_recent_bc                 12180 non-null  float64
 55  mths_since_recent_inq                12180 non-null  float64
 56  num_accts_ever_120_pd                12180 non-null  float64
 57  num_actv_bc_tl                       12180 non-null  float64
 58  num_actv_rev_tl                      12180 non-null  float64
 59  num_bc_sats                          12180 non-null  float64
 60  num_bc_tl                            12180 non-null  float64
 61  num_il_tl                            12180 non-null  float64
 62  num_op_rev_tl                        12180 non-null  float64
 63  num_rev_accts                        12180 non-null  float64
 64  num_rev_tl_bal_gt_0                  12180 non-null  float64
 65  num_sats                             12180 non-null  float64
 66  num_tl_120dpd_2m                     12180 non-null  float64
 67  num_tl_30dpd                         12180 non-null  float64
 68  num_tl_90g_dpd_24m                   12180 non-null  float64
 69  num_tl_op_past_12m                   12180 non-null  float64
 70  pct_tl_nvr_dlq                       12180 non-null  float64
 71  percent_bc_gt_75                     12180 non-null  float64
 72  pub_rec_bankruptcies                 12180 non-null  float64
 73  tax_liens                            12180 non-null  float64
 74  tot_hi_cred_lim                      12180 non-null  float64
 75  total_bal_ex_mort                    12180 non-null  float64
 76  total_bc_limit                       12180 non-null  float64
 77  total_il_high_credit_limit           12180 non-null  float64
 78  home_ownership_ANY                   12180 non-null  uint8
 79  home_ownership_MORTGAGE              12180 non-null  uint8
 80  home_ownership_OWN                   12180 non-null  uint8
 81  home_ownership_RENT                  12180 non-null  uint8
 82  verification_status_Not Verified     12180 non-null  uint8
 83  verification_status_Source Verified  12180 non-null  uint8
 84  verification_status_Verified         12180 non-null  uint8
 85  pymnt_plan_n                         12180 non-null  uint8
 86  initial_list_status_f                12180 non-null  uint8
 87  initial_list_status_w                12180 non-null  uint8
 88  application_type_Individual          12180 non-null  uint8
 89  application_type_Joint App           12180 non-null  uint8
 90  hardship_flag_N                      12180 non-null  uint8
 91  hardship_flag_Y                      12180 non-null  uint8
 92  debt_settlement_flag_N               12180 non-null  uint8
 93  debt_settlement_flag_Y               12180 non-null  uint8
dtypes: float64(76), int64(2), uint8(16)
memory usage: 7.4 MB

In [19]:
print(X_test['debt_settlement_flag_Y'])

0       0
1       0
2       0
3       0
4       0
       ..
4697    0
4698    0
4699    0
4700    0
4701    0
Name: debt_settlement_flag_Y, Length: 4702, dtype: int64

In [21]:
print(X_test['debt_settlement_flag_N'])

0       1
1       1
2       1
3       1
4       1
       ..
4697    1
4698    1
4699    1
4700    1
4701    1
Name: debt_settlement_flag_N, Length: 4702, dtype: uint8

In [8]:
y_train.value_counts()

low_risk     6090
high_risk    6090
Name: loan_status, dtype: int64

In [9]:
X_test = pd.get_dummies(test_df.drop(columns=['loan_status']))
y_test = test_df['loan_status']

In [16]:
# add missing dummy variables to testing set
for col in X_train.columns:
    if col not in X_test.columns:
        X_test[col]=0

In [11]:
# train the Logistic Regression model on the unscaled data and print the model score

In [12]:
# train a Random Forest Classifier model and print the model score

In [13]:
# scale the data

In [14]:
# train the Logistic Regression model on the scaled data and print the model score

In [15]:
# train a Random Forest Classifier model on the scaled data and print the model score